In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the Dataset

df = pd.read_csv("Automobile_data lab 4 (2).csv")

In [3]:
# Verify and understand the Dataset

df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [4]:
# Standardised the data in the columns

df["normalized-losses"].replace("?",np.nan,inplace=True)

/tmp/ipykernel_1138/1575225448.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].replace("?",np.nan,inplace=True)

In [5]:
# Check for Null Values

df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [6]:
# Fill the missing Values

df["normalized-losses"] = pd.to_numeric(
    df["normalized-losses"],
    errors="coerce"
)

m=df["normalized-losses"].mean()
print("Mean of normalized-losses : ",m)
df["normalized-losses"].fillna(m,inplace=True)

Mean of normalized-losses :  122.0

/tmp/ipykernel_1138/4256064042.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].fillna(m,inplace=True)

In [7]:
# Verify

df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [8]:
# Do the same for Horse-power Column

#replace ? with null values in "horsepower" column permanently
df["horsepower"].replace("?",np.nan,inplace=True)
#change the datatype of df["horsepower"] column from object to float
#permanently
df["horsepower"]=df["horsepower"].astype("float")

df.isnull().sum()

/tmp/ipykernel_1138/299684932.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].replace("?",np.nan,inplace=True)

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           2
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [9]:
m=df["horsepower"].mean()
print("Mean of horsepower : ",m)
df["horsepower"].fillna(m,inplace=True)

Mean of horsepower :  104.25615763546799

/tmp/ipykernel_1138/1164251145.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].fillna(m,inplace=True)

In [10]:
# separate numerical type column and object type column and store in new dataset

df_num=df.select_dtypes(["int64","float64"])#hold to int and float type data
df_cat=df.select_dtypes(object)#hold object type data

In [11]:
# Encode the Categorical Columns

from sklearn.preprocessing import LabelEncoder
for col in df_cat :
    le=LabelEncoder() #create the object of LabelEncoder class
    df_cat[col]=le.fit_transform(df_cat[col])

In [12]:
# Verify

df_cat.head()

   make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [13]:
# Concatenation of both dataset df_num and df_cat and hold new dataset df_new

df_new=pd.concat([df_num,df_cat],axis=1) #axis=1 column wise
df_new.head()

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,13495,0,1,0,2,0,0
1,3,122.0,64.1,48.8,130,111.0,21,27,16500,0,1,0,2,0,0
2,1,122.0,65.5,52.4,152,154.0,19,26,16500,0,1,2,2,0,5
3,2,164.0,66.2,54.3,109,102.0,24,30,13950,1,1,3,1,0,3
4,2,164.0,66.4,54.3,136,115.0,18,22,17450,1,1,3,0,0,3

In [14]:
# Select independent means input variables(X) and target means dependent variable(Y)

X=df_new.drop("price",axis=1)
#apart from price, all columns hold in X variable
Y=df_new["price"]
#output variable

In [15]:
# Train test split 70%-30%

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                              random_state=1)

In [16]:
# Check the shape of test and train data

X_train.shape,X_test.shape

((143, 14), (62, 14))

In [17]:
# Apply StandardScaler on X_train and X_test

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [18]:
# Verify

X_train

array([[ 1.69785729,  0.02383412,  0.12469565, ...,  1.17275014,
        -0.14638501,  0.00639503],
       [-1.42488988,  0.02383412,  0.21756793, ...,  1.17275014,
        -0.14638501, -2.73707423],
       [-0.64420309, -1.38767531, -1.12908013, ..., -2.35784501,
        -0.14638501,  0.00639503],
       ...,
       [ 1.69785729,  0.7123753 ,  2.07501352, ...,  1.17275014,
        -0.14638501,  1.83537454],
       [ 0.91717049, -1.31882119, -1.03620785, ..., -2.35784501,
        -0.14638501,  0.92088479],
       [-0.64420309, -0.52699883, -0.38610189, ..., -0.59254744,
        -0.14638501,  0.00639503]])

In [19]:
# Task 2: Build and Train Linear Regression Model
# 1 Import Linear Regression

from sklearn.linear_model import LinearRegression

In [20]:
# 2 Create Model Object

lr=LinearRegression()

In [21]:
# 3 Train the Model with 70% data

lr.fit(X_train,Y_train)

LinearRegression()

In [22]:
# Task 3: Predict Vehicle Prices

# Generate Predictions
y_pred = lr.predict(X_test)

In [23]:
# View Predicted Prices

y_pred[:10]

array([ 6147.97177535,  6877.02018581,  5163.92272988,  6529.64152282,
        9097.48416127, 26360.34172002,  7459.86435141,   877.82049881,
        5144.01614104, 13519.72327075])

In [53]:
# ML LAB 5 - Evaluate Regression Model Performance
# Check the training score on training data

lr.score(X_train,Y_train)

0.8504573774895474

In [25]:
# Check slope or coefficient of each input , use inbuilt method coef_

lr.coef_

array([   57.81895665,    44.47885193,  1700.08139295,   918.27940669,
        4046.25518791,  -450.43882012,  1968.72478882, -2781.47379917,
       -1253.87858019,  -178.99929397,  -149.85563859,  1058.52249069,
        2352.26450278,   309.65276269])

In [26]:
# Check testing score with 30% data

lr.score(X_test,Y_test)

0.7965566780397384

In [27]:
# Create a dictionary which hold input column and coefficient of input

dict={'features':X.columns,'Slope':lr.coef_}
df1=pd.DataFrame(dict)
df1

             features        Slope
0           symboling    57.818957
1   normalized-losses    44.478852
2               width  1700.081393
3              height   918.279407
4         engine-size  4046.255188
5          horsepower  -450.438820
6            city-mpg  1968.724789
7         highway-mpg -2781.473799
8                make -1253.878580
9           fuel-type  -178.999294
10         body-style  -149.855639
11       drive-wheels  1058.522491
12    engine-location  2352.264503
13        engine-type   309.652763

In [28]:
# Task 2: Apply Lasso Regression
# 1 Call inbuilt class Lasso

from sklearn.linear_model import Lasso

In [29]:
# 2 Select the right value of lambda /alpha in lasso, use simple technique

for i in range(200,1001,50): #start=200 stop=1001-1=1000 step=+50
    #create the object of Lasso class , passing the value of lambda
    l1=Lasso(i) #first i=200 , next i=250 ......
    #automatic write formula RSS+i*sum(abs(all coef))
    #train the model with 70% data using Lasso class , use fit() inbuilt
    #method of Lasso class
    l1.fit(X_train,Y_train)
    print("Value of Lambda : ",i)
    #check training score
    print("Training Score : ",l1.score(X_train,Y_train))
    #check testing score
    print("Testing Score : ",l1.score(X_test,Y_test))

Value of Lambda :  200
Training Score :  0.8410262816516455
Testing Score :  0.8111395722615142
Value of Lambda :  250
Training Score :  0.8385340173594726
Testing Score :  0.8105498997329942
Value of Lambda :  300
Training Score :  0.8354878961834389
Testing Score :  0.8094641048334433
Value of Lambda :  350
Training Score :  0.8319938320056115
Testing Score :  0.8079346980993205
Value of Lambda :  400
Training Score :  0.8284657641792199
Testing Score :  0.8061490778483928
Value of Lambda :  450
Training Score :  0.8249546529678113
Testing Score :  0.8041489036760304
Value of Lambda :  500
Training Score :  0.8210304998885254
Testing Score :  0.8017878944315399
Value of Lambda :  550
Training Score :  0.8166932955129319
Testing Score :  0.7990660335452213
Value of Lambda :  600
Training Score :  0.8119430443772861
Testing Score :  0.7959832844784963
Value of Lambda :  650
Training Score :  0.8067797434912503
Testing Score :  0.7925396011412089
Value of Lambda :  700
Training Score :  0.8018558303409655
Testing Score :  0.788982628108363
Value of Lambda :  750
Training Score :  0.7978566473416827
Testing Score :  0.7856542048320498
Value of Lambda :  800
Training Score :  0.7935816605078392
Testing Score :  0.7821357320480606
Value of Lambda :  850
Training Score :  0.7890308610369865
Testing Score :  0.7784272113835824
Value of Lambda :  900
Training Score :  0.7842042570823878
Testing Score :  0.7745286406360254
Value of Lambda :  950
Training Score :  0.7791274649239102
Testing Score :  0.7704701520045811
Value of Lambda :  1000
Training Score :  0.7754550114623461
Testing Score :  0.7681983507406608

In [30]:
# 3 Check coefficient /slope of each input/features after apply lasso

l1.coef_

array([  -0.        ,    0.        , 1149.39028092,    0.        ,
       4149.53419025,    0.        ,   -0.        , -441.14217416,
         -0.        ,   -0.        ,   -0.        ,  376.53222035,
       1077.64509062,    0.        ])

In [31]:
# 4 Add new column of slope in existing dataframe df1 after apply Lasso

df1['Slope_Lasso']=l1.coef_
df1

             features        Slope  Slope_Lasso
0           symboling    57.818957    -0.000000
1   normalized-losses    44.478852     0.000000
2               width  1700.081393  1149.390281
3              height   918.279407     0.000000
4         engine-size  4046.255188  4149.534190
5          horsepower  -450.438820     0.000000
6            city-mpg  1968.724789    -0.000000
7         highway-mpg -2781.473799  -441.142174
8                make -1253.878580    -0.000000
9           fuel-type  -178.999294    -0.000000
10         body-style  -149.855639    -0.000000
11       drive-wheels  1058.522491   376.532220
12    engine-location  2352.264503  1077.645091
13        engine-type   309.652763     0.000000

In [32]:
# 5 Create the Lasso Regression Model

lasso_model = Lasso(alpha= 200)

In [33]:
# 6 Train the Model

lasso_model.fit(X_train, Y_train)

Lasso(alpha=200)

In [35]:
#  7 Generate Predictions

lasso_pred = lasso_model.predict(X_test)

In [36]:
# 8 Create the Lasso Regression Model

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE :", mean_absolute_error(Y_test, lasso_pred))
print("MSE :", mean_squared_error(Y_test, lasso_pred))
print("R² Score :", r2_score(Y_test, lasso_pred))

MAE : 2350.473190835319
MSE : 11380696.984090814
R² Score : 0.8111395722615142

In [37]:
# Task 3: Apply Ridge Regression
# Call Ridge class inbuilt class

from sklearn.linear_model import Ridge

In [38]:
# 2 Find range of lambda 0-50

for i in range(0,51): #start=0 stop=51-1=50 step=+1
    #create the object of Ridge means L2 and passing the value of lambda
    l2=Ridge(i)
    #train the model with 70% data using Ridge class , use fit() inbuilt
    #method of Ridge class
    l2.fit(X_train,Y_train)
    print("Value of Lambda : ",i)
    #check training score
    print("Training Score : ",l2.score(X_train,Y_train))
    #check testing score
    print("Testing Score : ",l2.score(X_test,Y_test))

Value of Lambda :  0
Training Score :  0.8504573774895473
Testing Score :  0.7965566780397383
Value of Lambda :  1
Training Score :  0.8502107737350233
Testing Score :  0.7997849983168293
Value of Lambda :  2
Training Score :  0.849720842460161
Testing Score :  0.8020904988940025
Value of Lambda :  3
Training Score :  0.8491421996271185
Testing Score :  0.8038550529198802
Value of Lambda :  4
Training Score :  0.8485240352668717
Testing Score :  0.8052538108138244
Value of Lambda :  5
Training Score :  0.8478855977809376
Testing Score :  0.8063836531598355
Value of Lambda :  6
Training Score :  0.8472358385089226
Testing Score :  0.8073052711461921
Value of Lambda :  7
Training Score :  0.8465795576778711
Testing Score :  0.808060017457221
Value of Lambda :  8
Training Score :  0.8459196258570562
Testing Score :  0.8086777500683582
Value of Lambda :  9
Training Score :  0.8452578949328051
Testing Score :  0.8091809348336709
Value of Lambda :  10
Training Score :  0.8445956184203912
Testing Score :  0.8095869965126927
Value of Lambda :  11
Training Score :  0.8439336681239732
Testing Score :  0.8099097663196718
Value of Lambda :  12
Training Score :  0.8432726575220612
Testing Score :  0.8101604250480486
Value of Lambda :  13
Training Score :  0.8426130181419964
Testing Score :  0.810348145688699
Value of Lambda :  14
Training Score :  0.8419550499978528
Testing Score :  0.8104805472403599
Value of Lambda :  15
Training Score :  0.8412989565174477
Testing Score :  0.8105640245910257
Value of Lambda :  16
Training Score :  0.8406448695496873
Testing Score :  0.8106039940681196
Value of Lambda :  17
Training Score :  0.839992867686238
Testing Score :  0.8106050798587369
Value of Lambda :  18
Training Score :  0.839342989897074
Testing Score :  0.8105712579176033
Value of Lambda :  19
Training Score :  0.8386952457865311
Testing Score :  0.810505968655318
Value of Lambda :  20
Training Score :  0.8380496233617765
Testing Score :  0.8104122062805996
Value of Lambda :  21
Training Score :  0.8374060949430385
Testing Score :  0.8102925904090421
Value of Lambda :  22
Training Score :  0.8367646216707996
Testing Score :  0.8101494240162459
Value of Lambda :  23
Training Score :  0.8361251569452963
Testing Score :  0.8099847407479734
Value of Lambda :  24
Training Score :  0.8354876490487859
Testing Score :  0.8098003438458773
Value of Lambda :  25
Training Score :  0.8348520431395898
Testing Score :  0.8095978384041502
Value of Lambda :  26
Training Score :  0.8342182827617065
Testing Score :  0.8093786582751028
Value of Lambda :  27
Training Score :  0.8335863109800704
Testing Score :  0.8091440886470049
Value of Lambda :  28
Training Score :  0.8329560712261568
Testing Score :  0.8088952850962918
Value of Lambda :  29
Training Score :  0.8323275079193717
Testing Score :  0.8086332897482775
Value of Lambda :  30
Training Score :  0.8317005669149516
Testing Score :  0.8083590450517141
Value of Lambda :  31
Training Score :  0.8310751958178029
Testing Score :  0.8080734055728376
Value of Lambda :  32
Training Score :  0.8304513441929954
Testing Score :  0.8077771481367201
Value of Lambda :  33
Training Score :  0.8298289636968761
Testing Score :  0.8074709805825294
Value of Lambda :  34
Training Score :  0.8292080081475228
Testing Score :  0.8071555493507738
Value of Lambda :  35
Training Score :  0.8285884335491727
Testing Score :  0.8068314460819144
Value of Lambda :  36
Training Score :  0.8279701980820675
Testing Score :  0.8064992133746469
Value of Lambda :  37
Training Score :  0.8273532620666546
Testing Score :  0.8061593498270685
Value of Lambda :  38
Training Score :  0.826737587909123
Testing Score :  0.8058123144635596
Value of Lambda :  39
Training Score :  0.8261231400337108
Testing Score :  0.8054585306335859
Value of Lambda :  40
Training Score :  0.8255098848060085
Testing Score :  0.8050983894549708
Value of Lambda :  41
Training Score :  0.8248977904505288
Testing Score :  0.804732252862953
Value of Lambda :  42
Training Score :  0.8242868269650557
Testing Score :  0.804360456317024
Value of Lambda :  43
Training Score :  0.8236769660337007
Testing Score :  0.8039833112098058
Value of Lambda :  44
Training Score :  0.8230681809401207
Testing Score :  0.8036011070157723
Value of Lambda :  45
Training Score :  0.822460446481988
Testing Score :  0.8032141132121976
Value of Lambda :  46
Training Score :  0.8218537388875107
Testing Score :  0.802822581000171
Value of Lambda :  47
Training Score :  0.8212480357345804
Testing Score :  0.8024267448496716
Value of Lambda :  48
Training Score :  0.8206433158729407
Testing Score :  0.8020268238894507
Value of Lambda :  49
Training Score :  0.8200395593496377
Testing Score :  0.8016230231596999
Value of Lambda :  50
Training Score :  0.8194367473379025
Testing Score :  0.8012155347431369

In [39]:
# 3 Check coefficient after apply Ridge

l2.coef_
df1['Slope_Ridge']=l2.coef_
df1

             features        Slope  Slope_Lasso  Slope_Ridge
0           symboling    57.818957    -0.000000  -177.699126
1   normalized-losses    44.478852     0.000000    41.394288
2               width  1700.081393  1149.390281  1352.236132
3              height   918.279407     0.000000   689.297365
4         engine-size  4046.255188  4149.534190  2369.917291
5          horsepower  -450.438820     0.000000   790.358773
6            city-mpg  1968.724789    -0.000000  -420.154704
7         highway-mpg -2781.473799  -441.142174  -844.562855
8                make -1253.878580    -0.000000  -905.507222
9           fuel-type  -178.999294    -0.000000  -557.797113
10         body-style  -149.855639    -0.000000  -287.115577
11       drive-wheels  1058.522491   376.532220   981.743937
12    engine-location  2352.264503  1077.645091  1527.983482
13        engine-type   309.652763     0.000000   414.273427

In [40]:
# 4 Create the Ridge Regression Model

ridge_model = Ridge(alpha= 12)

In [41]:
# 5 Train the Model

ridge_model.fit(X_train, Y_train)

Ridge(alpha=12)

In [42]:
# 6 Generate Predictions

ridge_pred = ridge_model.predict(X_test)

In [43]:
# 7 Evaluate the Ridge Model

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE :", mean_absolute_error(Y_test, ridge_pred))
print("MSE :", mean_squared_error(Y_test, ridge_pred))
print("R² Score :", r2_score(Y_test, ridge_pred))

MAE : 2347.6119258273975
MSE : 11439700.22724082
R² Score : 0.8101604250480486

In [44]:
# Task 4: Compare All Three Models
# Create a Comparison Table

comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression"
    ],
    "MAE": [
        2465.395028223579,
        2346.9710123689783,
        2350.473190835319
    ],
    "MSE": [
        12262833.694863686,
        11433097.715870142,
        11380696.984090814
    ],
    "R2 Score": [
        0.7965006870725597,
        0.8102699924254559,
        0.8111395722615142
    ]
})

# Display the comparison table
comparison

               Model          MAE           MSE  R2 Score
0  Linear Regression  2465.395028  1.226283e+07  0.796501
1   Ridge Regression  2346.971012  1.143310e+07  0.810270
2   Lasso Regression  2350.473191  1.138070e+07  0.811140

In [52]:
# ML6: Evaluate Regression Model Performance
#Apply Regularization Techniques (Lasso & Ridge)
# Task 1: Review Model Predictions
# 1 - Review the Actual Values and Predicted Values, compare both, and record your observations based on how closely the predictions match the actual prices.

comparison = pd.DataFrame({ "Actual": Y_test, "Predicted": y_pred })
comparison.head(10)

     Actual     Predicted
78     6669   6147.971775
97     7999   6877.020186
151    6338   5163.922730
44    10000   6529.641523
40    10295   9097.484161
67    25552  26360.341720
98     8249   7459.864351
18     5151    877.820499
152    6488   5144.016141
62    10245  13519.723271

In [46]:
# Task 2: Calculate Mean Absolute Error (MAE)
# 1 Import the required library

from sklearn.metrics import mean_absolute_error

In [47]:
# 2 Calculate MAE

mae = mean_absolute_error(Y_test, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 2464.0068217581615

In [48]:
# 3 Task 3: Calculate Mean Squared Error (MSE)
# 1 Import the required library

from sklearn.metrics import mean_squared_error

In [49]:
# Calculate MAE

mse = mean_squared_error(Y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 12259459.688784504

In [56]:
# Root Mean Sqaure Error
import math
rmse=math.sqrt(mse)
print(" Root Mean Sqaure Error:",mse)

 Root Mean Sqaure Error: 12259459.688784504

In [50]:
# Task 4: Evaluate R² Score
#  1 Import the required library
from sklearn.metrics import r2_score

In [51]:
# 2 Calculate the R² Score

r2 = r2_score(Y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.7965566780397384